
import React from 'react';
import { motion } from 'framer-motion';
import { BarChart, Search, Zap, Globe, FileText, CheckCircle } from 'lucide-react';

export function Features() {
    const features = [
        {
            icon: <Globe className="w-6 h-6 text-brand-500" />,
            title: "AI Visibility Audit",
            description: "See exactly how ChatGPT, Claude, Perplexity, and Google Gemini see your brand. We test 50+ queries to determine your 'Share of Model'.",
        },
        {
            icon: <Zap className="w-6 h-6 text-amber-500" />,
            title: "Answer Engine Optimization",
            description: "Don't just rank for links. Rank for *answers*. We analyze your site's structure to ensure LLMs can parse and cite your content.",
        },
        {
            icon: <BarChart className="w-6 h-6 text-emerald-500" />,
            title: "Tiered Reporting",
            description: "Three distinct views: Executive Brief (ROI focus), Action Plan (Dev team focus), and Technical Data (Deep dive).",
        },
        {
            icon: <Search className="w-6 h-6 text-blue-500" />,
            title: "Deep Competitor Benchmarking",
            description: "Compare your AI visibility score against your top 3 competitors. See where they are winning the 'Citation Wars'.",
        },
        {
            icon: <FileText className="w-6 h-6 text-indigo-500" />,
            title: "Premium PDF Export",
            description: "Generate client-ready, boardroom-quality PDF reports with a single click. White-label ready.",
        },
        {
            icon: <CheckCircle className="w-6 h-6 text-teal-500" />,
            title: "Data Accuracy Verification",
            description: "Our proprietary crawler validates every claim against real-time data, ensuring 100% factual reporting.",
        },
    ];

    return (
        <div className="py-12 md:py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-16">
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                    The Future of SEO is <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-600 to-indigo-600">Invisible</span>
                </h2>
                <p className="text-xl text-slate-600 max-w-2xl mx-auto">
                    Traditional SEO tools track blue links. We track the answers generated by the world's most powerful AI models.
                </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                {features.map((feature, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow"
                    >
                        <div className="w-12 h-12 bg-slate-50 rounded-xl flex items-center justify-center mb-6">
                            {feature.icon}
                        </div>
                        <h3 className="text-xl font-semibold text-slate-900 mb-3">{feature.title}</h3>
                        <p className="text-slate-600 leading-relaxed">
                            {feature.description}
                        </p>
                    </motion.div>
                ))}
            </div>
        </div>
    );
}
