"""
Report branding integration module.

Provides functions to apply tenant branding to HTML and PDF reports.
"""

import re
from typing import Any, Optional

from sqlalchemy.orm import Session

from .service import DEFAULT_BRANDING, BrandingService


def get_report_branding(db: Session, tenant_id: Optional[str]) -> dict[str, Any]:
    """
    Get branding configuration for report generation.

    Args:
        db: Database session
        tenant_id: Tenant ID (optional)

    Returns:
        Branding configuration dict with logo_url, primary_color,
        secondary_color, and footer_text
    """
    if not tenant_id:
        return DEFAULT_BRANDING.copy()

    service = BrandingService(db)
    return service.get_report_branding(tenant_id)


def apply_html_branding(html_content: str, branding: dict[str, Any]) -> str:
    """
    Apply branding to HTML report content.

    Replaces default colors and footer text with tenant branding.

    Args:
        html_content: Original HTML content
        branding: Branding configuration dict

    Returns:
        HTML content with branding applied
    """
    primary_color = branding.get("primary_color", DEFAULT_BRANDING["primary_color"])
    secondary_color = branding.get("secondary_color", DEFAULT_BRANDING["secondary_color"])
    footer_text = branding.get("footer_text", DEFAULT_BRANDING["footer_text"])
    logo_url = branding.get("logo_url")

    # Replace primary color (#1a73e8 is default blue)
    html_content = html_content.replace("#1a73e8", primary_color)
    html_content = html_content.replace("#1A73E8", primary_color)

    # Replace secondary color (#34a853 is default green)
    html_content = html_content.replace("#34a853", secondary_color)
    html_content = html_content.replace("#34A853", secondary_color)

    # Replace gradient colors in header
    html_content = re.sub(
        r'linear-gradient\(135deg,\s*#1a73e8,\s*#0d47a1\)',
        f'linear-gradient(135deg, {primary_color}, {_darken_color(primary_color, 0.3)})',
        html_content,
        flags=re.IGNORECASE
    )

    # Replace footer text
    html_content = html_content.replace(
        "Generated by SEO Health Report System",
        footer_text or DEFAULT_BRANDING["footer_text"]
    )

    # Add logo if provided
    if logo_url:
        logo_html = f'''
            <div style="text-align: center; margin-bottom: 20px;">
                <img src="{logo_url}" alt="Company Logo" style="max-height: 60px; max-width: 200px;">
            </div>
        '''
        # Insert after opening container div
        html_content = html_content.replace(
            '<div class="container">',
            f'<div class="container">{logo_html}'
        )

    return html_content


def get_pdf_branding_colors(branding: dict[str, Any]) -> dict[str, str]:
    """
    Get color configuration for PDF report generation.

    Args:
        branding: Branding configuration dict

    Returns:
        Dict with color keys for PDF generator
    """
    primary = branding.get("primary_color", DEFAULT_BRANDING["primary_color"])
    secondary = branding.get("secondary_color", DEFAULT_BRANDING["secondary_color"])

    return {
        "primary": primary,
        "secondary": secondary,
        "warning": "#fbbc04",
        "danger": "#ea4335",
        "dark": "#202124",
        "light": "#f8f9fa",
        "grade_a": "#28a745",
        "grade_b": "#5cb85c",
        "grade_c": "#f0ad4e",
        "grade_d": "#d9534f",
        "grade_f": "#c9302c",
    }


def get_pdf_footer_text(branding: dict[str, Any]) -> str:
    """
    Get footer text for PDF reports.

    Args:
        branding: Branding configuration dict

    Returns:
        Footer text string
    """
    return branding.get("footer_text") or DEFAULT_BRANDING["footer_text"]


def _darken_color(hex_color: str, factor: float = 0.2) -> str:
    """
    Darken a hex color by a factor.

    Args:
        hex_color: Hex color string (e.g., "#1E3A8A")
        factor: Darkening factor (0-1)

    Returns:
        Darkened hex color
    """
    hex_color = hex_color.lstrip("#")

    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)

    r = max(0, int(r * (1 - factor)))
    g = max(0, int(g * (1 - factor)))
    b = max(0, int(b * (1 - factor)))

    return f"#{r:02x}{g:02x}{b:02x}"


def _lighten_color(hex_color: str, factor: float = 0.2) -> str:
    """
    Lighten a hex color by a factor.

    Args:
        hex_color: Hex color string (e.g., "#1E3A8A")
        factor: Lightening factor (0-1)

    Returns:
        Lightened hex color
    """
    hex_color = hex_color.lstrip("#")

    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)

    r = min(255, int(r + (255 - r) * factor))
    g = min(255, int(g + (255 - g) * factor))
    b = min(255, int(b + (255 - b) * factor))

    return f"#{r:02x}{g:02x}{b:02x}"


def generate_css_variables(branding: dict[str, Any]) -> str:
    """
    Generate CSS custom properties from branding.

    Args:
        branding: Branding configuration dict

    Returns:
        CSS string with :root variables
    """
    primary = branding.get("primary_color", DEFAULT_BRANDING["primary_color"])
    secondary = branding.get("secondary_color", DEFAULT_BRANDING["secondary_color"])

    return f"""
    :root {{
        --brand-primary: {primary};
        --brand-primary-dark: {_darken_color(primary, 0.3)};
        --brand-primary-light: {_lighten_color(primary, 0.3)};
        --brand-secondary: {secondary};
        --brand-secondary-dark: {_darken_color(secondary, 0.3)};
        --brand-secondary-light: {_lighten_color(secondary, 0.3)};
    }}
    """
