"""
Meta Tags Generator

Generates optimized meta tags based on page content analysis.
"""

import html
from typing import Any


def generate_meta_tags(page_data: dict[str, Any]) -> str:
    """
    Generate optimized meta tags for a page.

    Args:
        page_data: Page analysis data including title, description, content

    Returns:
        HTML meta tags as a string
    """
    url = page_data.get("url", "")
    title = page_data.get("title", "")
    description = page_data.get("meta_description", "")
    h1 = ""
    h1_tags = page_data.get("h1_tags", [])
    if h1_tags:
        h1 = h1_tags[0] if isinstance(h1_tags, list) else str(h1_tags)

    # Generate title if missing or too short
    if not title or len(title) < 20:
        title = h1 if h1 else f"Page - {_extract_domain(url)}"

    # Ensure title is optimal length (50-60 chars)
    if len(title) > 60:
        title = title[:57] + "..."

    # Generate description if missing
    if not description or len(description) < 50:
        content_preview = page_data.get("content_preview", "")
        if content_preview:
            description = content_preview[:155] + "..." if len(content_preview) > 155 else content_preview
        else:
            description = f"Learn more about {title}. Visit our website for detailed information."

    # Ensure description is optimal length (150-160 chars)
    if len(description) > 160:
        description = description[:157] + "..."

    # Sanitize for HTML output
    safe_title = html.escape(title)
    safe_description = html.escape(description)
    safe_url = html.escape(url)

    tags = [
        "<!-- SEO Meta Tags - Generated by SEO Health Report -->",
        f'<title>{safe_title}</title>',
        f'<meta name="description" content="{safe_description}">',
        "",
        "<!-- Open Graph Tags -->",
        f'<meta property="og:title" content="{safe_title}">',
        f'<meta property="og:description" content="{safe_description}">',
        f'<meta property="og:url" content="{safe_url}">',
        '<meta property="og:type" content="website">',
        "",
        "<!-- Twitter Card Tags -->",
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{safe_title}">',
        f'<meta name="twitter:description" content="{safe_description}">',
        "",
        "<!-- Canonical URL -->",
        f'<link rel="canonical" href="{safe_url}">',
    ]

    return "\n".join(tags)


def _extract_domain(url: str) -> str:
    """Extract domain from URL."""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    return parsed.netloc or url
