"""Unit tests for report branding integration."""

from unittest.mock import MagicMock, patch

from packages.seo_health_report.branding.report_integration import (
    _darken_color,
    _lighten_color,
    apply_html_branding,
    generate_css_variables,
    get_pdf_branding_colors,
    get_pdf_footer_text,
    get_report_branding,
)
from packages.seo_health_report.branding.service import DEFAULT_BRANDING


class TestGetReportBranding:
    """Test get_report_branding function."""

    def test_returns_defaults_when_no_tenant(self):
        mock_db = MagicMock()
        result = get_report_branding(mock_db, None)

        assert result == DEFAULT_BRANDING

    def test_uses_branding_service_when_tenant_provided(self):
        mock_db = MagicMock()

        with patch("packages.seo_health_report.branding.report_integration.BrandingService") as MockService:
            MockService.return_value.get_report_branding.return_value = {
                "logo_url": "https://example.com/logo.png",
                "primary_color": "#FF5733",
                "secondary_color": "#33FF57",
                "footer_text": "Custom Footer",
            }

            result = get_report_branding(mock_db, "tenant_123")

        assert result["logo_url"] == "https://example.com/logo.png"
        assert result["primary_color"] == "#FF5733"


class TestApplyHtmlBranding:
    """Test apply_html_branding function."""

    def test_replaces_primary_color(self):
        html = '<div style="color: #1a73e8;">Test</div>'
        branding = {"primary_color": "#FF5733", "secondary_color": "#33FF57"}

        result = apply_html_branding(html, branding)

        assert "#FF5733" in result
        assert "#1a73e8" not in result

    def test_replaces_secondary_color(self):
        html = '<div style="color: #34a853;">Test</div>'
        branding = {"primary_color": "#1E3A8A", "secondary_color": "#AABBCC"}

        result = apply_html_branding(html, branding)

        assert "#AABBCC" in result
        assert "#34a853" not in result

    def test_replaces_footer_text(self):
        html = '<p>Generated by SEO Health Report System</p>'
        branding = {"footer_text": "Powered by Acme Corp"}

        result = apply_html_branding(html, branding)

        assert "Powered by Acme Corp" in result
        assert "Generated by SEO Health Report System" not in result

    def test_adds_logo_when_provided(self):
        html = '<div class="container">Content</div>'
        branding = {"logo_url": "https://example.com/logo.png"}

        result = apply_html_branding(html, branding)

        assert 'src="https://example.com/logo.png"' in result

    def test_handles_missing_branding_values(self):
        html = '<div style="color: #1a73e8;">Test</div>'
        branding = {}

        result = apply_html_branding(html, branding)

        assert "#1E3A8A" in result  # Uses default


class TestGetPdfBrandingColors:
    """Test get_pdf_branding_colors function."""

    def test_returns_custom_colors(self):
        branding = {
            "primary_color": "#FF5733",
            "secondary_color": "#33FF57",
        }

        result = get_pdf_branding_colors(branding)

        assert result["primary"] == "#FF5733"
        assert result["secondary"] == "#33FF57"
        assert result["warning"] == "#fbbc04"
        assert result["danger"] == "#ea4335"

    def test_uses_defaults_when_not_provided(self):
        branding = {}

        result = get_pdf_branding_colors(branding)

        assert result["primary"] == DEFAULT_BRANDING["primary_color"]
        assert result["secondary"] == DEFAULT_BRANDING["secondary_color"]


class TestGetPdfFooterText:
    """Test get_pdf_footer_text function."""

    def test_returns_custom_footer(self):
        branding = {"footer_text": "Custom Footer"}

        result = get_pdf_footer_text(branding)

        assert result == "Custom Footer"

    def test_returns_default_when_not_provided(self):
        branding = {}

        result = get_pdf_footer_text(branding)

        assert result == DEFAULT_BRANDING["footer_text"]

    def test_returns_default_when_none(self):
        branding = {"footer_text": None}

        result = get_pdf_footer_text(branding)

        assert result == DEFAULT_BRANDING["footer_text"]


class TestColorManipulation:
    """Test color darkening and lightening functions."""

    def test_darken_color(self):
        result = _darken_color("#ffffff", 0.5)
        assert result == "#7f7f7f"

    def test_darken_color_by_30_percent(self):
        result = _darken_color("#1E3A8A", 0.3)
        assert result.startswith("#")
        assert len(result) == 7

    def test_darken_pure_black_stays_black(self):
        result = _darken_color("#000000", 0.5)
        assert result == "#000000"

    def test_lighten_color(self):
        result = _lighten_color("#000000", 0.5)
        assert result == "#7f7f7f"

    def test_lighten_pure_white_stays_white(self):
        result = _lighten_color("#ffffff", 0.5)
        assert result == "#ffffff"


class TestGenerateCssVariables:
    """Test generate_css_variables function."""

    def test_generates_css_root_variables(self):
        branding = {
            "primary_color": "#1E3A8A",
            "secondary_color": "#3B82F6",
        }

        result = generate_css_variables(branding)

        assert ":root {" in result
        assert "--brand-primary: #1E3A8A" in result
        assert "--brand-secondary: #3B82F6" in result
        assert "--brand-primary-dark:" in result
        assert "--brand-primary-light:" in result

    def test_uses_defaults_when_not_provided(self):
        branding = {}

        result = generate_css_variables(branding)

        assert DEFAULT_BRANDING["primary_color"] in result
        assert DEFAULT_BRANDING["secondary_color"] in result
